import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { NavAppBanner } from './NavAppBanner';

export default {
  title: 'Fullmenu/T앱',
  component: NavAppBanner,
  argTypes: {},
} as ComponentMeta<typeof NavAppBanner>;

const Template: ComponentStory<typeof NavAppBanner> = function fun(args) {
  return <NavAppBanner {...args} />;
};

export const Default = Template.bind({});
Default.args = {
  tApp: [
    {
      menuId: 'M002428',
      bnnrSeq: '1',
      expsStaDtm: '202301170000',
      expsEndDtm: '202512310000',
      imgLinkUrl: '/product/apps/app?appId=TW50000107',
      imgLinkTrgtClCd: '1',
      bnnrFileNm: 't.png',
      bnnrFilePathNm:
        'https://s3-tworld-stg-an2-cdn-origin-mobile.s3-ap-northeast-2.amazonaws.com/adminupload/bnnr/25767/1360/84206930.png',
      bnnrExpsSeq: '1',
      bnnrImgAltCtt: 'A.(에이닷)',
      bnnrDesc: null,
      bnnrLocCd: 'r',
      billYn: 'Y',
      oferStcCd: 'CMMA_A11_B3-162',
      chnlClCd: '01,02,03',
      anchTagInfo: null,
      linkTypCd: 'S',
      bnnrHtmlCtt: null,
      bnnrTypCd: null,
      titleNm: 'A.(에이닷)',
      bgColor: null,
      bnnrImgTitNm: 'A.(에이닷)',
      rollYn: null,
      scrnTypCd: null,
      tagMappInfo: null,
      popupNexpsPrdCd: null,
      popupExpsObjCd: null,
      stplNagreeSegExpsYn: null,
      inetSvcExpsYn: null,
      iptvSvcExpsYn: null,
      combSvcExpsYn: null,
    },
    {
      menuId: 'M002428',
      bnnrSeq: '2',
      expsStaDtm: '202301170000',
      expsEndDtm: '202512310000',
      imgLinkUrl: '/product/apps/app?appId=TW50000049',
      imgLinkTrgtClCd: '1',
      bnnrFileNm: 't.png',
      bnnrFilePathNm:
        'https://s3-tworld-stg-an2-cdn-origin-mobile.s3-ap-northeast-2.amazonaws.com/adminupload/bnnr/25767/1360/84175186.png',
      bnnrExpsSeq: '2',
      bnnrImgAltCtt: 'ifland',
      bnnrDesc: null,
      bnnrLocCd: 'r',
      billYn: 'Y',
      oferStcCd: 'CMMA_A11_B3-163',
      chnlClCd: '01,02,03',
      anchTagInfo: null,
      linkTypCd: 'S',
      bnnrHtmlCtt: null,
      bnnrTypCd: null,
      titleNm: 'ifland',
      bgColor: null,
      bnnrImgTitNm: 'ifland',
      rollYn: null,
      scrnTypCd: null,
      tagMappInfo: null,
      popupNexpsPrdCd: null,
      popupExpsObjCd: null,
      stplNagreeSegExpsYn: null,
      inetSvcExpsYn: null,
      iptvSvcExpsYn: null,
      combSvcExpsYn: null,
    },
    {
      menuId: 'M002428',
      bnnrSeq: '3',
      expsStaDtm: '202301170000',
      expsEndDtm: '202512310000',
      imgLinkUrl: '/product/apps/app?appId=TW50000005',
      imgLinkTrgtClCd: '1',
      bnnrFileNm: 'T_call.png',
      bnnrFilePathNm:
        'https://s3-tworld-stg-an2-cdn-origin-mobile.s3-ap-northeast-2.amazonaws.com/adminupload/bnnr/11460/06096/1626516876.png',
      bnnrExpsSeq: '3',
      bnnrImgAltCtt: '통화매니저',
      bnnrDesc: null,
      bnnrLocCd: 'r',
      billYn: 'Y',
      oferStcCd: 'CMMA_A11_B3-164',
      chnlClCd: '01,02,03',
      anchTagInfo: null,
      linkTypCd: 'S',
      bnnrHtmlCtt: null,
      bnnrTypCd: null,
      titleNm: '통화매니저',
      bgColor: null,
      bnnrImgTitNm: '통화매니저',
      rollYn: null,
      scrnTypCd: null,
      tagMappInfo: null,
      popupNexpsPrdCd: null,
      popupExpsObjCd: null,
      stplNagreeSegExpsYn: null,
      inetSvcExpsYn: null,
      iptvSvcExpsYn: null,
      combSvcExpsYn: null,
    },
    {
      menuId: 'M002428',
      bnnrSeq: '4',
      expsStaDtm: '202301170000',
      expsEndDtm: '202512310000',
      imgLinkUrl: '/product/apps/app?appId=TW50000020',
      imgLinkTrgtClCd: '1',
      bnnrFileNm: 't-t.png',
      bnnrFilePathNm:
        'https://s3-tworld-stg-an2-cdn-origin-mobile.s3-ap-northeast-2.amazonaws.com/adminupload/bnnr/25767/1360/796156173.png',
      bnnrExpsSeq: '4',
      bnnrImgAltCtt: 'T 멤버십',
      bnnrDesc: null,
      bnnrLocCd: 'r',
      billYn: 'Y',
      oferStcCd: 'CMMA_A11_B3-165',
      chnlClCd: '01,02,03',
      anchTagInfo: null,
      linkTypCd: 'S',
      bnnrHtmlCtt: null,
      bnnrTypCd: null,
      titleNm: 'T 멤버십',
      bgColor: null,
      bnnrImgTitNm: 'T 멤버십',
      rollYn: null,
      scrnTypCd: null,
      tagMappInfo: null,
      popupNexpsPrdCd: null,
      popupExpsObjCd: null,
      stplNagreeSegExpsYn: null,
      inetSvcExpsYn: null,
      iptvSvcExpsYn: null,
      combSvcExpsYn: null,
    },
  ],
};
